{
  "default": true,
  "no-hard-tabs": true,
  "whitespace": true,
  "MD003": { "style": "atx" }, # Header style
  "MD004": { "style": "asterisk" }, # Unordered list style
  "MD007": { "indent": 4 }, # Unordered list indentation
  "MD013": false, # Line length
  "MD024": false, # Duplicate headers
  "MD033": false, # Inline HTML
  "MD041": false # First line should be H1
}
