name: CI

on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
      name: Lint
      runs-on: ubuntu-latest

      steps:
        - name: Setup Node
          uses: actions/setup-node@v2.1.2

        - name: Checkout
          uses: actions/checkout@v2

        - name: Install markdownlinter-cli
          run: npm install markdownlint-cli

        - name: Lint all markdown files
          run: ./node_modules/.bin/markdownlint ./ --ignore node_modules --ignore v5

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
